Fix failing spec where current_scope is undefined
Some tests were failing to define the current_scope. Using `root_element`
sets the current_scope for the matcher.

```
Failures:

  1) Subject filter check each accordion section has aria-control set to the section-content id
     Failure/Error: expect(accordion_section).to have_selector("div##{expected_control_ids[counter]}")

     NoMethodError:
       undefined method `current_scope' for #<Capybara::Node::Element:0x00007fdfb24b93a0>
     # ./spec/features/result_filters/subjects_spec.rb:236:in `block (4 levels) in <top (required)>'
     # ./spec/features/result_filters/subjects_spec.rb:233:in `each'
     # ./spec/features/result_filters/subjects_spec.rb:233:in `each_with_index'
     # ./spec/features/result_filters/subjects_spec.rb:233:in `block (3 levels) in <top (required)>'

  2) Subject filter with no selected subjects should not expand any accordion sections
     Failure/Error: expect(filter_page.subject_areas.first).to have_no_css(".govuk-accordion__section--expanded")

     NoMethodError:
       undefined method `current_scope' for #<Capybara::Node::Element:0x00007fdfaae137f0>
     # ./spec/features/result_filters/subjects_spec.rb:287:in `block (3 levels) in <top (required)>'

Finished in 16.79 seconds (files took 4.7 seconds to load)
309 examples, 2 failures

Failed examples:

rspec ./spec/features/result_filters/subjects_spec.rb:225 # Subject filter check each accordion section has aria-control set to the section-content id
rspec ./spec/features/result_filters/subjects_spec.rb:286 # Subject filter with no selected subjects should not expand any accordion sections
```